### ISSUE TITLE
issue with @sholace package in google chrome (v114.0.5735.133)

### ISSUE THREAD

**Issue by ardihikaru** [medblocks/medblocks-ui#51]
Hi. 
I have a problem with **@shoelace-style/shoelace** package when opening my web app in Google Chrome:
![image](https://github.com/medblocks/medblocks-ui/assets/9791562/eb6e5b22-bf33-4302-8a5e-2bdedeeb381d)
![image](https://github.com/medblocks/medblocks-ui/assets/9791562/439e606e-82cc-49c8-8aa0-4b654069b89b)
```
reposition() {
            this.open && this.popover.update()  ----> this one
        }
        async handleOpenChange() {
            if (!this.disabled)
                if (this.updateAccessibleTrigger(),
                this.open) {
                    Ybe(this, "sl-show"),
                    this.panel.addEventListener("sl-activate", this.handleMenuItemActivate),
                    this.panel.addEventListener("sl-select", this.handlePanelSelect),
                    document.addEventListener("keydown", this.handleDocumentKeyDown),
                    document.addEventListener("mousedown", this.handleDocumentMouseDown),
                    await Obe(this),
                    this.popover.update(),  ----> this one
                    this.panel.hidden = !1;
                    const {keyframes: e, options: t} = Kbe(this, "dropdown.show");
```

It only happens in **Google Chrome version 114.0.5735.133**.
Tried to forcefully increase the version to `^2.4.0`, but the problem persists.

Any solution for this issue?

Thanks,
Ardi

**Comment by sidharthramesh** [comment]
This has been fixed in the latest version of Medblocks ui. You’ll need to use it with shoelace version 2.0.0-beta.71.

**Comment by JokoHadi** [comment]
I have same issue for this one
my google chrome version is 114.0.5735.134

I've updated medblock-ui to the latest version (0.0.179), and it seems to be using "@shoelace-style/shoelace": "2.0.0-beta.71"
But I still get same errors

Did I miss something?

**Comment by sidharthramesh** [comment]
Do you have a repo with the minimal code to reproduce this issue?

**Comment by sidharthramesh** [comment]
@ATHULKNAIR FYI

**Comment by ardihikaru** [comment]
Hi, thanks for the solution.
I updated the version as mentioned and managed to solve it.
here is the update on the `package.json`:
```
  "devDependencies": {
    ...
    "svelte": "^3.59.1",
    ...
  "dependencies": {
    ...
    "@shoelace-style/shoelace": "^2.0.0-beta.71",
    "medblocks-ui": "^0.0.179",
```

So, I will close this issue. 
Many thanks.
